apiVersion: v1
kind: Pod
metadata:
  name: result-aap-pod
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: result-aap
      image: kodekloud/examplevotingapp_result:v1
      ports:
        - containerPort: 80
