apiVersion: v1
kind: Pod
metadata:
  name: voting-aap-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: voting-aap
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80
